version: '3.8'

services:
  fastapi-langchain:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .:/usr/src
    stdin_open: true
    tty: true
